### ISSUE TITLE
fix patch error 「patch: **** malformed patch at line 1187」

### ISSUE THREAD

**Issue by shuxiao9058** [charlesw/tesseract-vs2012#4]
please replace "vs2013+64bit_support.patch" with this file <https://raw.githubusercontent.com/shuxiao9058/tesseract-vs2012/master/vs2013+64bit_support.patch>.

**Comment by brucardoso2** [comment]
Same for me.
fatal: corrupt patch at line 1188

**Comment by charlesw** [comment]
Okay I'll have another look at this. One question though did you try applying the patch to the svn repo or git repo for Tesseract. This is important as the patch was made before they switched over to git. I'll see if I can update it to include a patch for the git repo.

**Comment by brucardoso2** [comment]
git repo

**Comment by charlesw** [comment]
I've added the git version of the patch to the dev branch. Can you test if it's working for you? I'm currently going through the complete build process from a blank repo as discussed in #5.

**Comment by charlesw** [comment]
Trash that the patch doesn't work. Seeing if I can get it working now...

**Comment by charlesw** [comment]
Fixed git patch for Tesseract in latest release.

**Comment by waynebekker** [comment]
Thank you for all your effort Charles.
