### ISSUE TITLE
There are issues with the project files and liblebt code

### ISSUE THREAD

**Issue by waynebekker** [charlesw/tesseract-vs2012#5]
This is much appreciated, however you will not build successfully unless you have every version of each dependancy correct. you guys can build most likely only because you have been doing this for a while. I challenge you to follow your own instructions, using even your own sources to build this on a fresh windows install == FAIL

It is great having the bindings C# in the project, but again there is so much that does not work due to "fixed paths" in additional directories and dependencies that simply does not enable you to compile this unless you know EXACTLY whats going on. Perhaps an update is needed!!!! Again,  I challenge you to follow your own instructions, using even your own sources to build this on a fresh windows install?

**Comment by charlesw** [comment]
Fair enough, I'll see what I can do.

**Comment by waynebekker** [comment]
Thank you for responding. I did not expect that. You all do amazing work for which many of us owe you great thank yous, and I look forward to your results when you do have the time. I have tried no less than 4 times over the last two weeks without success, particularly once I get to the bindings (c#). I have successfully managed to get the Vs2008 versions to build tesseract 3.02, but would really like to get the 2012 or 2013 versions working with the 3.03 and .net winforms application. The issues start already with building leptonica 1.71 failing with numerous errors.

**Comment by waynebekker** [comment]
Just some feedback. I had a chat to someone who knows this inners of c+ better and have managed to fix the issues and build successfully now. It turned out to be code issues with liblept1-71 and path configurations in the projects.

Herewith steps to fix the issues, sadly i cannot attach a word document so pictures of it should do or I can email it to you to consider. I hope my experiences can assist someone else should they have trouble.

Thank you again for your hard work and apologies for my rant caused by a (now) lack of hair.

![capture01](https://cloud.githubusercontent.com/assets/9925418/6187027/1f69a990-b38a-11e4-86a1-79d2cdb845a3.JPG)
![capture02](https://cloud.githubusercontent.com/assets/9925418/6187031/24641c50-b38a-11e4-833f-123a09c82680.JPG)
![capture03](https://cloud.githubusercontent.com/assets/9925418/6187035/27587f14-b38a-11e4-9e64-629ea2c03bb5.JPG)
![capture04](https://cloud.githubusercontent.com/assets/9925418/6187037/29732966-b38a-11e4-9c69-ecb6a59bf325.JPG)
![capture05](https://cloud.githubusercontent.com/assets/9925418/6187040/2c3acb22-b38a-11e4-878e-5c21964e5371.JPG)
![capture06](https://cloud.githubusercontent.com/assets/9925418/6187041/2f718862-b38a-11e4-90f3-64f5f2f20d72.JPG)

**Comment by charlesw** [comment]
I've gone through the process of generating a new build from start to finish from a blank repo and updated the doco and provided patch to reflect that the Tesseract team have switched to git for version management.
