### ISSUE TITLE
vs2015 C1189 error snprintf conflict

### ISSUE THREAD

**Issue by eloops** [charlesw/tesseract-vs2012#8]
Looks like vs2015 trips over the _snprintf defs, I commented them out, it compiles okay without them in there. Also, the afxres.h <> windows.h thing.

Thank you for your work =)

**Comment by juanllopez** [comment]
Hello, 
I'm having the same problem you did, can you please explain where and how you commented the snprintf defs? 
Sorry if this is an obvious question but I am basically new to programming and IDE's.

Thank you

**Comment by eloops** [comment]
In `tesseract/ccutil/platform.h`, comment out:
````
#if defined(_MSC_VER)
#define snprintf _snprintf
#if (_MSC_VER < 1900)
#define vsnprintf _vsnprintf
#endif /* (_MSC_VER <= 1400) */
#endif /* defined(_MSC_VER) */
````

In `tesseract/viewer/svutil.h` comment out:
````
#define snprintf _snprintf
#if (_MSC_VER < 1900)
#define vsnprintf _vsnprintf
#endif
````
To comment out the line, you add a `//` to it. 
There will be a few instances where the code calls `#include <afxres.h>`. This fails with the community edition of vs2015 (I think). Change these occurances to `#include <windows.h>`. 

Those are the specific changes I made to get it to compile using vs2015. If it doesn't work for you I can't help you.
